### ISSUE TITLE
Compiler error when coupling with OpenFAST

### ISSUE THREAD

**Issue by koodlyakshay** [NREL/SOWFA-6#49]
Hello,

I am facing the following error when I try to link the latest version of OpenFAST to SOWFA-6

`horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.C: In member function ‘void Foam::turbineModels::horizontalAxisWindTurbinesALMOpenFAST::sendInput()’:
horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.C:444:6: error: ‘class fast::fastInputs’ has no member named ‘numScInputs’
  444 |   fi.numScInputs = numSuperControllerOutputs ;
      |      ^~~~~~~~~~~
horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.C:445:6: error: ‘class fast::fastInputs’ has no member named ‘numScOutputs’
  445 |   fi.numScOutputs = numSuperControllerInputs ;`

I have also attached the log file with the full output when I try to build SOWFA-6. 

[log_sowfa_build_error.txt](https://github.com/NREL/SOWFA-6/files/9673728/log_sowfa_build_error.txt).

Steps I have done so far - Installed OpenFOAM-6 ( not sure if relevant, but I had to use c++=14 standard instead of default because CGAL would give errors otherwise), master branch of OpenFAST with the same compilers and then tried to build SOWFA-6. Other executables build properly. 

OS: Ubuntu 18
Compilers: gcc 11.2.0

Thanks for the help.

**Comment by rthedin** [comment]
Dear Akshay,
The reason such line was commented out is that the turbine modeling capabilities present in the solver `superDeliciousVanilla.turbine` are being ported to the single unified solver `superDeliciousVanilla`. I recommend getting what is currently PR https://github.com/NREL/SOWFA-6/pull/50 (soon to be merged into dev) and give that a shot. I believe it will fix your error.

**Comment by svv73** [comment]
Hello,

I am too facing the following error when I try to link the latest version of OpenFAST to SOWFA-6

horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.C: In member function ‘void Foam::turbineModels::horizontalAxisWindTurbinesALMOpenFAST::sendInput()’:
horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.C:482:31: error: ‘__gnu_cxx::__alloc_traits<std::allocator<fast::globTurbineDataType> >::value_type {aka struct fast::globTurbineDataType}’ has no member named ‘forcePtsBladeDistributionType’
     fi.globTurbineData[iTurb].forcePtsBladeDistributionType = bladePointDistType[iTurb];

**Comment by yisehakabreham** [comment]
Dear @rthedin,

I am facing similar SOWFA-6 compilation errors while compiling with OpenFAST-3.3. I am using Ubuntu 18.04 OS and gcc-7.5.0. SOWFA-2.4.x works fine on the machine, but i am not sure about the requirements for SOWFA-6.
Would you please take a look at the log.Allwmake file attached here.

Thank you for your guidance. 

[log_Allwmake.txt](https://github.com/NREL/SOWFA-6/files/11172025/log_Allwmake.txt)

Yisehak

**Comment by koodlyakshay** [comment]
Hi Yisehak,

We realized those errors are due to the OpenFAST. From v3, the super controller stuff has apparently changed in OpenFAST. You will have to use older versions i.e anything older than 3. We managed to get it working with v2.4.

Akshay

**Comment by Didi-X** [comment]
@rthedin I want to confirm whether the current SOWFA does not support the operation of beamdyn module. When I set CompElast in the.fst file to 1=ElastoDyn, the coupling case can run. But when I set it to 2=ElastoDyn + BeamDyn for blades. It starts with the following error:
Running BEM.
[0] #0 Foam::error::printStack(Foam::Ostream&) at ??:?
[0] https://github.com/NREL/SOWFA/pull/1 Foam::sigSegv::sigHandler(int) at ??:?
[0] https://github.com/NREL/SOWFA/issues/2 ? in "/lib/x86_64-linux-gnu/libpthread.so.0"
[0] https://github.com/NREL/SOWFA/issues/3 modmesh_mp_meshcopy_ at ??:?
[0] https://github.com/NREL/SOWFA/issues/4 openfoam_mp_init_opfm_ at ??:?
[0] https://github.com/NREL/SOWFA/issues/5 fast_subs_mp_fast_initializeall_ at ??:?
[0] https://github.com/NREL/SOWFA/pull/6 fast_subs_mp_fast_initializeall_t_ at ??:?
[0] https://github.com/NREL/SOWFA/pull/7 FAST_OpFM_Init at ??:?
[0] https://github.com/NREL/SOWFA/issues/8 fast::OpenFAST::init() at ??:?
[0] https://github.com/NREL/SOWFA/issues/9 Foam::turbineModels::horizontalAxisWindTurbinesALMOpenFAST::initialize() at ??:?
[0] https://github.com/NREL/SOWFA/issues/10 Foam::turbineModels::horizontalAxisWindTurbinesALMOpenFAST::horizontalAxisWindTurbinesALMOpenFAST(Foam::GeometricField<Foam::Vector, Foam::fvPatchField, Foam::volMesh> const&) at ??:?

I want to confirm is whether the error is caused by the use of the beamdyn module.I checked the horizontalAxisWindTurbinesALMOpenFAST in the make/options .It contains the beamdyn library
-laerodynlib \
-lbeamdynlib \
-lelastodynlib
I look forward to hearing from you. Thank you very much

**Comment by rthedin** [comment]
Closing this. Feel free to re-open if there are further questions.
